---
title: "20230316_GBS_BetaDiversity"
output: pdf_document
date: "2023-03-16"
author: Elise S. Cowley
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("knitr")
library("knitr")
#install.packages("readxl")
library("readxl")
#install.packages("dplyr")
library("dplyr")
#install.packages("ggplot2")
library("ggplot2")
install.packages("stringr")          # Install stringr package
library("stringr")                   # Load stringr
#install.packages("phyloseq")
source("https://raw.githubusercontent.com/joey711/phyloseq/master/inst/scripts/installer.R",
       local = TRUE)


library("phyloseq")
```

```{r}
BrayCurtis_TableDistances <- read.csv("~/Library/CloudStorage/Box-Box/Hryckowian Lab/GBS-Presence and Abundance/16S_rRNA_Analysis_Ibrahim/R files/distance_asatable_bray.csv")
View(BrayCurtis_TableDistances)
```

```{r IZC Code-BrayCurtisPlot}

phyloseq_obj_beta_GBS <- readRDS("~/Library/CloudStorage/Box-Box/Hryckowian Lab/GBS-Presence and Abundance/16S_rRNA_Analysis_Ibrahim/R files/QWAR_sub_GBS_norm_trim.PHY")

require("phyloseq")
require("dplyr")
require("reshape2")
require("ggplot2")

#based on: https://www.biostars.org/p/452069/

#bray CURTIS

# calc distances
#bc = phyloseq::distance(QWAR_sub_GBS_norm_trim, "bray")
bc <- phyloseq::distance(phyloseq_obj_beta_GBS, "bray")
bc.m <- reshape2::melt(as.matrix(bc))

# # remove self-comparisons
bc.m = bc.m %>%
   filter(as.character(Var1) != as.character(Var2)) %>%
   mutate_if(is.factor, as.character)

# get sample data (S4 error OK and expected)
sample_data <- data.frame(sample_data(phyloseq_obj_beta_GBS))

sample_data <- sample_data %>%
  select("X.SampleID", "GBS_pre") %>%
  mutate_if(is.factor,as.character)

# combined distances with sample data
colnames(sample_data) <- c("Var1", "Type1")
bc.sampledata = left_join(bc.m, sample_data, by = "Var1")

colnames(sample_data) <- c("Var2", "Type2")
bc.sampledata = left_join(bc.sampledata, sample_data, by = "Var2")

#install.packages("tidyr")
library("tidyr")
variables_forplot_bray <- bc.sampledata %>% 
  unite(Pair, c("Type2", "Type1"))

variables_forplot_bray$Pair <- as.factor(variables_forplot_bray$Pair)

levels(variables_forplot_bray$Pair)

GBS_BC_YesNo_YesYes_NoNo <- filter(variables_forplot_bray, `Pair` == "No_No" | `Pair` == "Yes_No" |`Pair` == "Yes_Yes")


```

```{r BrayCurtis-3groups}
GBS_braycurtis_plot <- ggplot(GBS_BC_YesNo_YesYes_NoNo, aes(x=value, y=Pair)) + 
  geom_violin()
GBS_braycurtis_plot

    
GBS_braycurtis_boxplot <- ggplot(GBS_BC_YesNo_YesYes_NoNo, aes(x=value, y=Pair, color=`Pair`)) +
  theme_bw() +
  geom_boxplot() + 
  theme(legend.position="none", plot.title = element_text(hjust = 0.5))+
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black") + coord_flip() +
  labs(x="Bray-Curtis Distance",y ="Comparison Groups", title="Bray-Curtis Distance Based on Group B Streptococcus Presence") 
  #scale_color_manual(values=c("#6BBAE5","#C5692D", "#514289"))
  #geom_jitter(width = 0.06, height = 0.1, alpha = 0.7)
  #facet_wrap(~ Type1, scales = "free_x") +
  #theme(axis.text.x=element_text(angle = 90, hjust = 1, vjust = 0.5)) +
GBS_braycurtis_boxplot

GBS_braycurtis_boxplot_v2 <- GBS_braycurtis_boxplot +coord_flip(xlim=c(0,1.25))+  scale_color_manual(values=c("#6BBAE5","#C5692D", "#514289"))
GBS_braycurtis_boxplot_v2

ggsave("20230406_GBS_BrayCurtis_boxplot_AllGroups.pdf", plot = GBS_braycurtis_boxplot_v2, width = 6, height = 4)

#make violin plot
GBS_braycurtis_violin <- ggplot(GBS_BC_YesNo_YesYes_NoNo, aes(x=value, y=Pair)) +
  theme_bw() +
  geom_violin() +  
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black")
  #geom_jitter(width = 0.06, height = 0.1, alpha = 0.7)
  #facet_wrap(~ Type1, scales = "free_x") +
  #theme(axis.text.x=element_text(angle = 90, hjust = 1, vjust = 0.5)) +
GBS_braycurtis_violin
GBS_braycurtis_violin_2 <- GBS_braycurtis_violin + coord_flip()
GBS_braycurtis_violin_2


# Compute the analysis of variance
#https://www.scribbr.com/statistics/one-way-anova/
res.aov_BC <- aov(value ~ Pair, data = GBS_BC_YesNo_YesYes_NoNo)
# Summary of the analysis
summary(res.aov_BC)
#p-value of F statistic is < 2E-16; p-value of the pair is significant so grouping does have effect on BC distance

#ANOVA will tell you if there are differences among the levels of the independent variable, but not which differences are significant. To find how the treatment levels differ from one another, perform a TukeyHSD (Tukey’s Honestly-Significant Difference) post-hoc test.

#The Tukey test runs pairwise comparisons among each of the groups, and uses a conservative error estimate to find the groups which are statistically different from one another.
TukeyHSD(res.aov_BC)
#Yes_No have lower BC indices than No_No - statistically significant
#Yes_Yes have lower BC indices than No_No - statistically significant
#Yes_Yes have lower BC indices than Yes_No - statistically significant
#We found a statistically-significant difference in average Bray-Curtis distance according to presence or absence of GBS. A Tukey post-hoc test revealed significant pairwise differences in comparing the intergroup distance for samples with GBS and those without GBS with an average difference of 0.042 (P<0.001), intergroup differences for samples with and without GBS compared to distances between only samples without GBS with an average difference of 0.020 (P<0.001), and intergroup differences for samples with and without GBS compared to distances between only samples with GBS with an average difference of 0.022 (P<0.001).
```


```{r BrayCurtis-old-dontuse}
GBS_braycurtis_plot <- ggplot(variables_forplot_bray, aes(x=value, y=Pair)) + 
  geom_violin()
GBS_braycurtis_plot

    
GBS_braycurtis_boxplot <- ggplot(variables_forplot_bray, aes(x=value, y=Pair)) +
  theme_bw() +
  geom_boxplot() +  
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black") + coord_flip() +
  labs(x="Bray-Curtis Distance",y ="Comparison Groups", title="Bray-Curtis Distance Based on Group B Streptococcus Presence")
  #geom_jitter(width = 0.06, height = 0.1, alpha = 0.7)
  #facet_wrap(~ Type1, scales = "free_x") +
  #theme(axis.text.x=element_text(angle = 90, hjust = 1, vjust = 0.5)) +
GBS_braycurtis_boxplot

ggsave("20230326_GBS_BrayCurtis_boxplot_AllGroups.pdf", plot = GBS_braycurtis_boxplot, width = 6, height = 4)

#make violin plot
GBS_braycurtis_violin <- ggplot(variables_forplot_bray, aes(x=value, y=Pair)) +
  theme_bw() +
  geom_violin() +  
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black")
  #geom_jitter(width = 0.06, height = 0.1, alpha = 0.7)
  #facet_wrap(~ Type1, scales = "free_x") +
  #theme(axis.text.x=element_text(angle = 90, hjust = 1, vjust = 0.5)) +
GBS_braycurtis_violin
GBS_braycurtis_violin_2 <- GBS_braycurtis_violin + coord_flip()
GBS_braycurtis_violin_2


# Compute the analysis of variance
res.aov <- aov(value ~ Pair, data = variables_forplot)
# Summary of the analysis
summary(res.aov)

TukeyHSD(res.aov)


write.csv(bc.sd,file="/Users/ibrahimzuniga/Documents/SuenLab/GBS/distance_asatable_bray.csv")
```


```{r WeightedUnifrac}
# calc distances
#wu = phyloseq::distance(QWAR_sub_GBS_norm_trim, "bray")
wu <- phyloseq::distance(phyloseq_obj_beta_GBS, "wunifrac")
wu.m <- reshape2::melt(as.matrix(wu))

# # remove self-comparisons
wu.m = wu.m %>%
   filter(as.character(Var1) != as.character(Var2)) %>%
   mutate_if(is.factor, as.character)

# get sample data (S4 error OK and expected)
sample_data <- data.frame(sample_data(phyloseq_obj_beta_GBS))

sample_data <- sample_data %>%
  select("X.SampleID", "GBS_pre") %>%
  mutate_if(is.factor,as.character)

# combined distances with sample data
colnames(sample_data) <- c("Var1", "Type1")
wu.sampledata = left_join(wu.m, sample_data, by = "Var1")

colnames(sample_data) <- c("Var2", "Type2")
wu.sampledata = left_join(wu.sampledata, sample_data, by = "Var2")

#install.packages("tidyr")
#library("tidyr")
variables_forplot_weightedunifrac <- wu.sampledata %>% 
  unite(Pair, c("Type2", "Type1"))

variables_forplot_weightedunifrac$Pair <- as.factor(variables_forplot_weightedunifrac$Pair)

levels(variables_forplot_weightedunifrac$Pair)

GBS_WU_YesNo_YesYes_NoNo <- filter(variables_forplot_weightedunifrac, `Pair` == "No_No" | `Pair` == "Yes_No" |`Pair` == "Yes_Yes")

    
GBS_weightedunifrac_boxplot <- ggplot(GBS_WU_YesNo_YesYes_NoNo, aes(x=value, y=Pair, color = `Pair`)) +
  geom_boxplot() +
  theme_bw() +
  theme(legend.position="none", plot.title = element_text(hjust = 0.5))+
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black") + coord_flip() +
  labs(x="Weighted Unifrac Distance",y ="Comparison Groups", title="Weighted Unifrac Distance Based on Group B Streptococcus Presence")
  #geom_jitter(width = 0.06, height = 0.1, alpha = 0.7)
  #facet_wrap(~ Type1, scales = "free_x") +
  #theme(axis.text.x=element_text(angle = 90, hjust = 1, vjust = 0.5)) +
GBS_weightedunifrac_boxplot

GBS_weightedunifrac_boxplot_2 <- GBS_weightedunifrac_boxplot + coord_flip(xlim=c(0,0.8))+ scale_color_manual(values=c("#6BBAE5","#C5692D", "#514289"))
GBS_weightedunifrac_boxplot_2
ggsave("20230406_GBS_WeightedUnifrac_boxplot_AllGroups.pdf", plot = GBS_weightedunifrac_boxplot_2, width = 6.5, height = 4)


# Compute the analysis of variance
#https://www.scribbr.com/statistics/one-way-anova/
res.aov_WU <- aov(value ~ Pair, data = GBS_WU_YesNo_YesYes_NoNo)
# Summary of the analysis
summary(res.aov_WU)
#p-value of F statistic is < 2E-16; p-value of the pair is significant so grouping does have effect on BC distance

#ANOVA will tell you if there are differences among the levels of the independent variable, but not which differences are significant. To find how the treatment levels differ from one another, perform a TukeyHSD (Tukey’s Honestly-Significant Difference) post-hoc test.

#The Tukey test runs pairwise comparisons among each of the groups, and uses a conservative error estimate to find the groups which are statistically different from one another.
TukeyHSD(res.aov_WU)
#Yes_No have lower WU indices than No_No - statistically significant
#Yes_Yes have lower WU indices than No_No - statistically significant
#Yes_Yes have lower WU indices than Yes_No - statistically significant
#We found a statistically-significant difference in average weighted unifrac distance according to presence or absence of GBS. A Tukey post-hoc test revealed significant pairwise differences in comparing the intergroup distance for samples with GBS and those without GBS with an average difference of 0.003 (P<0.001), intergroup differences for samples with and without GBS compared to distances between only samples without GBS with an average difference of 0.001 (P<0.001), and intergroup differences for samples with and without GBS compared to distances between only samples with GBS with an average difference of 0.001 (P=0.001).
```




```{r Unifrac}
# calc distances
u <- phyloseq::distance(phyloseq_obj_beta_GBS, "unifrac")
u.m <- reshape2::melt(as.matrix(u))

# # remove self-comparisons
u.m = u.m %>%
   filter(as.character(Var1) != as.character(Var2)) %>%
   mutate_if(is.factor, as.character)

# get sample data (S4 error OK and expected)
sample_data <- data.frame(sample_data(phyloseq_obj_beta_GBS))

sample_data <- sample_data %>%
  select("X.SampleID", "GBS_pre") %>%
  mutate_if(is.factor,as.character)

# combined distances with sample data
colnames(sample_data) <- c("Var1", "Type1")
u.sampledata = left_join(u.m, sample_data, by = "Var1")

colnames(sample_data) <- c("Var2", "Type2")
u.sampledata = left_join(u.sampledata, sample_data, by = "Var2")

#install.packages("tidyr")
#library("tidyr")
variables_forplot_unifrac <- u.sampledata %>% 
  unite(Pair, c("Type2", "Type1"))

variables_forplot_unifrac$Pair <- as.factor(variables_forplot_unifrac$Pair)

levels(variables_forplot_unifrac$Pair)


GBS_UF_YesNo_YesYes_NoNo <- filter(variables_forplot_unifrac, `Pair` == "No_No" | `Pair` == "Yes_No" |`Pair` == "Yes_Yes")

    
GBS_unifrac_boxplot <- ggplot(GBS_UF_YesNo_YesYes_NoNo, aes(x=value, y=Pair, color = `Pair`)) +
  geom_boxplot() +
  theme_bw() +
  theme(legend.position="none", plot.title = element_text(hjust = 0.5))+
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black") + coord_flip() +
  labs(x="Unifrac Distance",y ="Comparison Groups", title="Unifrac Distance Based on Group B Streptococcus Presence")
  #geom_jitter(width = 0.06, height = 0.1, alpha = 0.7)
  #facet_wrap(~ Type1, scales = "free_x") +
  #theme(axis.text.x=element_text(angle = 90, hjust = 1, vjust = 0.5)) +
GBS_unifrac_boxplot

GBS_unifrac_boxplot_2 <- GBS_unifrac_boxplot + coord_flip(xlim=c(0,1.4))+ scale_color_manual(values=c("#6BBAE5","#C5692D", "#514289"))
GBS_unifrac_boxplot_2
ggsave("20230406_GBS_Unifrac_boxplot_AllGroups.pdf", plot = GBS_unifrac_boxplot_2, width = 6, height = 4)
    
# Compute the analysis of variance
#https://www.scribbr.com/statistics/one-way-anova/
res.aov_UF <- aov(value ~ Pair, data = GBS_UF_YesNo_YesYes_NoNo)
# Summary of the analysis
summary(res.aov_UF)
#p-value of F statistic is < 2E-16; p-value of the pair is significant so grouping does have effect on BC distance

#ANOVA will tell you if there are differences among the levels of the independent variable, but not which differences are significant. To find how the treatment levels differ from one another, perform a TukeyHSD (Tukey’s Honestly-Significant Difference) post-hoc test.

#The Tukey test runs pairwise comparisons among each of the groups, and uses a conservative error estimate to find the groups which are statistically different from one another.
TukeyHSD(res.aov_UF)
#Yes_No have lower BC indices than No_No - statistically significant
#Yes_Yes have lower BC indices than No_No - statistically significant
#Yes_Yes have lower BC indices than Yes_No - statistically significant
#We found a statistically-significant difference in average unifrac distance according to presence or absence of GBS. A Tukey post-hoc test revealed significant pairwise differences in comparing the intergroup distance for samples with GBS and those without GBS with an average difference of 0.024 (P<0.001), intergroup differences for samples with and without GBS compared to distances between only samples without GBS with an average difference of 0.011 (P<0.001), and intergroup differences for samples with and without GBS compared to distances between only samples with GBS with an average difference of 0.013 (P<0.001).

```
