---
title: "20230309_GBSPresenceandAbundance"
output: pdf_document
author: Elise S. Cowley
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("knitr")
library("knitr")
install.packages("readxl")
library("readxl")
install.packages("dplyr")
library("dplyr")
install.packages("ggplot2")
library("ggplot2")
```

```{r}

setwd("~/Library/CloudStorage/Box-Box/Hryckowian Lab/GBS-Presence and Abundance/WARRIOR - GBS qPCR")

GBS_qPCRSummary <- read_excel("~/Library/CloudStorage/Box-Box/Hryckowian Lab/GBS-Presence and Abundance/WARRIOR - GBS qPCR/20220721_qPCRSummary.xlsx")
View(GBS_qPCRSummary)

summary(GBS_qPCRSummary)
colnames(GBS_qPCRSummary)
setwd("~/Library/CloudStorage/Box-Box/Hryckowian Lab/GBS-Presence and Abundance/WARRIOR - GBS qPCR")

GBS_qPCRSummary <- read_excel("20220721_qPCRSummary.xlsx")
View(GBS_qPCRSummary)

summary(GBS_qPCRSummary)
colnames(GBS_qPCRSummary)

median(GBS_qPCRSummary$Age)
mean(GBS_qPCRSummary$Age)
min(GBS_qPCRSummary$Age)
max(GBS_qPCRSummary$Age)
IQR(GBS_qPCRSummary$Age)
sd(GBS_qPCRSummary$Age)



GBS_qPCRSummary$Gender<-as.character(GBS_qPCRSummary$Gender)
GBS_qPCRSummary["Gender"][GBS_qPCRSummary["Gender"] == "2"] <- "Female"
GBS_qPCRSummary["Gender"][GBS_qPCRSummary["Gender"] == "1"] <- "Male"


GBS_Gender_Freq <- GBS_qPCRSummary %>%
  group_by(Gender, `GBS Presence?`) %>%
  summarize(count=n())

GBS_Abundance <- filter(GBS_qPCRSummary, `GBS Presence?` == "Yes")
typeof(GBS_Abundance$`Avg Copy Number (copies/ng)`)
as.character(GBS_Abundance$`Avg Copy Number (copies/ng)`)
GBS_Abundance_2<-as.numeric(GBS_Abundance$`Avg Copy Number (copies/ng)`)
GBS_Abundance_2 <- mutate(GBS_Abundance, `Avg Copy Number (copies/ng)`= as.numeric(`Avg Copy Number (copies/ng)`))
typeof(GBS_Abundance_2$`Avg Copy Number (copies/ng)`)

median(GBS_Abundance_2$`Avg Copy Number (copies/ng)`)
mean(GBS_Abundance_2$`Avg Copy Number (copies/ng)`)
min(GBS_Abundance_2$`Avg Copy Number (copies/ng)`)
max(GBS_Abundance_2$`Avg Copy Number (copies/ng)`)

```


```{r Fig1A-CarriageFreq}

GBS_Gender_Freq_plot <- ggplot(GBS_Gender_Freq, aes(x=Gender, y=count, fill=`GBS Presence?`))+
  geom_bar(stat='identity')+
  theme_minimal()+
  theme_bw() +
  geom_text(aes(label=count), position = position_stack(vjust=0.5),colour = "white", size = 5) +
  scale_fill_discrete(name=NULL) + scale_fill_manual('GBS Detected', values=c("#6BBAE5","#514289")) +
  labs(y="Number of Participants",x ="Self-Identified Gender",title="Group B Streptococcus Carrier Frequency in Stool")
GBS_Gender_Freq_plot
ggsave("20230309_GBS_GenderFreq.pdf", plot = GBS_Gender_Freq_plot, width = 6, height = 4)
```

```{r}

chisq.test(GBS_Gender_Freq$Gender, GBS_Gender_Freq$`GBS Presence?`)
chisq.test(GBS_Gender_Freq$`GBS Presence?`, GBS_Gender_Freq$Gender)

chisq.test(GBS_qPCRSummary$Gender, GBS_qPCRSummary$`GBS Presence?`)

#Pearson's Chi-squared test with Yates' continuity correction

#data:  GBS_qPCRSummary$Gender and GBS_qPCRSummary$`GBS Presence?`
#X-squared = 1.6031e-06, df = 1, p-value = 0.999 - no significant difference between having GBS and not for gender
```

```{r Fig1B}
GBS_Abundance$`Avg Copy Number (copies/ng)`<-as.numeric(GBS_Abundance$`Avg Copy Number (copies/ng)`)

GBS_Abundance_plot_byGender_box <- ggplot(GBS_Abundance, aes(x=`Gender`, y=`Avg Copy Number (copies/ng)`, color = `Gender`)) +
  geom_boxplot(outlier.shape = NA) +  
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black")+
  geom_jitter(width = 0.06, height = 0.1, alpha = 0.7)+
  scale_y_continuous(trans='log10') + 
  theme_bw() +
  theme(legend.position="none", plot.title = element_text(hjust = 0.5))+
  labs(y="Average Copy Number (copies/ng starting DNA)",x ="Self-Identified Gender", title="Group B Streptococcus Abundance")
GBS_Abundance_plot_byGender_box
#GBS_Abundance_plot_byGender_box_v2 <- GBS_Abundance_plot_byGender_box + scale_color_manual(values=c("#5c1a33", "#f3c483"))
GBS_Abundance_plot_byGender_box_v2 <- GBS_Abundance_plot_byGender_box + scale_color_manual(values=c("#81974C","#68434E"))

GBS_Abundance_plot_byGender_box_v2
ggsave("20230309_GBS_Abundance_byGender_boxplot.pdf", plot = GBS_Abundance_plot_byGender_box_v2, width = 6, height = 4)
```

```{r Fig1B-noindivddatapoints}
GBS_Abundance$`Avg Copy Number (copies/ng)`<-as.numeric(GBS_Abundance$`Avg Copy Number (copies/ng)`)

GBS_Abundance_plot_byGender_box_noindivdatapoints <- ggplot(GBS_Abundance, aes(x=`Gender`, y=`Avg Copy Number (copies/ng)`, color = `Gender`)) +
  geom_boxplot() +  
  stat_summary(fun = "mean", geom = "point", shape = 5, size = 2, color = "black")+
  #geom_jitter(width = 0.06, height = 0.1, alpha = 0.2)+
  scale_y_continuous(trans='log10') + 
  theme_bw() +
  theme(legend.position="none", plot.title = element_text(hjust = 0.5))+
  labs(y="Average Copy Number (copies/ng starting DNA)",x ="Gender", title="Group B Streptococcus Abundance")
GBS_Abundance_plot_byGender_box_noindivdatapoints
GBS_Abundance_plot_byGender_box_noindivdatapoints_v2 <- GBS_Abundance_plot_byGender_box_noindivdatapoints + scale_color_manual(values=c("#5c1a33", "#f3c483"))
GBS_Abundance_plot_byGender_box_noindivdatapoints_v2
ggsave("20220920_GBS_Abundance_byGender_boxplot_noindividualdatapoints.pdf", plot = GBS_Abundance_plot_byGender_box_noindivdatapoints_v2, width = 6, height = 4)
```

```{r}
#test that the variances are the same and test if there is a statistically significant difference between abundances for females and males
abundance.gender.ftest <- var.test( `Avg Copy Number (copies/ng)` ~ Gender, data = GBS_Abundance)
abundance.gender.ftest
abundance.gender.ttest <- t.test(`Avg Copy Number (copies/ng)` ~ Gender, data = GBS_Abundance, var.equal = FALSE)
abundance.gender.ttest  #p-value = 0.4612, no difference in means of abundances for individuals who have GBS and who do not have GBS
```

```{r}
#summaries of abundances
summary(GBS_Abundance_2) 
#`Avg Copy Number (copies/ng)` ~ Gender, data = GBS_Abundance)
Abundance_Summaries_ByGender<-
  GBS_Abundance_2 %>% 
  group_by(`Gender`) %>% 
  summarise(mean=mean(`Avg Copy Number (copies/ng)`), 
            median=median(`Avg Copy Number (copies/ng)`), 
            n=n(), 
            sd = sd(`Avg Copy Number (copies/ng)`), 
            iqr=IQR(`Avg Copy Number (copies/ng)`),
            medianabsolutedeviation=mad(`Avg Copy Number (copies/ng)`),
            min=min(`Avg Copy Number (copies/ng)`),
            max=max(`Avg Copy Number (copies/ng)`),
            #quantile=quantile(`Avg Copy Number (copies/ng)`),
            first=first(`Avg Copy Number (copies/ng)`),
            last=last(`Avg Copy Number (copies/ng)`))
```



